Repository AmaliTech-Training-Academy/LetXChat, pull requests merged in 2023-04, with the labels that each got.

#1 Feature/signup backend
  app/Http/Controllers/API/AuthController.php
  app/Http/Requests/RegisterRequest.php
  app/Http/Resources/RegisterResource.php
  app/Models/User.php
  composer.lock
  database/migrations/2014_10_12_000000_create_users_table.php
  public/Picture1.jpg
  routes/api.php
Labels: enhancement

#2 Feature/landing page
  package.json
  src/App.jsx
  src/assets/Camera.svg
  src/assets/Edit Row.svg
  src/assets/Favorite.svg
  src/assets/Gear.svg
  src/assets/People.svg
  src/assets/Phone.svg
  src/assets/Search.svg
  src/assets/Upload.svg
  src/assets/Video Call.svg
  src/assets/collaboration-section.png
  src/assets/confirmation alert.svg
  src/assets/hero_1.png
  src/assets/hero_2.png
  src/assets/ion_logo-twitter.png
  src/assets/ion_logo-twitter.svg
  src/assets/logo.png
  src/assets/mdi_facebook.png
  src/assets/mdi_facebook.svg
  src/assets/playBtn.svg
  src/assets/profile camera.svg
  src/assets/profile picture.png
  src/assets/ri_instagram-fill.svg
  src/assets/uil_linkedin.svg
  src/components/Landing-Page/BodyContent.jsx
  src/components/Landing-Page/Footer.jsx
  src/components/Landing-Page/HomeBanner.jsx
  src/components/Landing-Page/Navbar.jsx
  src/components/Landing-Page/Newsletter.jsx
  src/main.jsx
  src/pages/Home.jsx
  src/routes/Router.jsx
  src/svg/Icons.jsx
Labels: enhancement

#3 Feature/signup
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/assets/camera.png
  src/assets/collaboration section.png
  src/assets/favicon.png
  src/assets/hero 1.png
  src/assets/hero 2.png
  src/assets/profile-picture.png
  src/colors.scss
  src/components/login/Login.jsx
  src/components/signup/SignUp.jsx
  src/index.scss
  src/schemas/index.js
Labels: enhancement

#4 Feature/login
  package-lock.json
  package.json
  src/App.jsx
  src/components/login/Login.jsx
  src/components/regModal/RegModal.jsx
  src/components/signup/SignUp.jsx
  src/schemas/index.js
Labels: enhancement

#5 Feature/login backend
  app/Http/Controllers/API/AuthController.php
  app/Http/Kernel.php
  app/Http/Requests/LoginRequest.php
  app/Models/User.php
  routes/api.php
Labels: enhancement

#7 Feature/landing page
  src/App.jsx
  src/components/Landing-Page/Navbar.jsx
  src/components/about/About.jsx
  src/components/contact/Contact.jsx
  src/components/layout/Layout.jsx
  src/pages/Home.jsx
  src/routes/Router.jsx
Labels: enhancement

#8 Feature/sidebar
  src/assets/Close.png
  src/assets/Edit.svg
  src/assets/ama.png
  src/assets/chef.png
  src/assets/king.png
  src/assets/kofi.png
  src/assets/mno.png
  src/assets/mum.png
  src/assets/sidebar_user.png
  src/components/layouts/MainLayout.jsx
  src/components/layouts/SidebarLayout.jsx
  src/components/sidebar/ChatCard.jsx
  src/components/sidebar/CreateGroup.jsx
  src/components/sidebar/CreateGroupSection.jsx
  src/components/sidebar/Search.jsx
  src/components/sidebar/Settings.jsx
  src/components/sidebar/Sidebar.jsx
  src/components/sidebar/UserCard.jsx
  src/routes/Router.jsx
Labels: enhancement

#10 Feature/generate chat id backend
  app/Http/Controllers/API/AuthController.php
  app/Http/Requests/LoginRequest.php
  app/Http/Requests/RegisterRequest.php
  app/Http/Resources/ProfileResource.php
  app/Http/Resources/RegisterResource.php
  app/Models/User.php
  composer.json
  composer.lock
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2023_04_05_160156_rename_employee_id_column_to_chat_id_in_users_table.php
Labels: enhancement

#11 feature/generateChatId-backend: updated id generation to check for null id
  app/Http/Controllers/API/AuthController.php
Labels: bug

#12 Feature/chat backend
  app/Events/NewChatMessage.php
  app/Http/Controllers/API/ChatMessageController.php
  app/Listeners/SendChatMessageNotification.php
  app/Models/ChatMessage.php
  app/Models/ChatRoom.php
  app/Models/User.php
  app/Providers/EventServiceProvider.php
  composer.json
  composer.lock
  config/app.php
  database/migrations/2023_04_06_103932_create_chat_messages_table.php
  database/migrations/2023_04_06_123219_add_message_column_to_chat_messages_table.php
  routes/api.php
  routes/channels.php
Labels: enhancement

#13 Feature/signup
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/app/store.js
  src/components/Landing-Page/BodyContent.jsx
  src/components/Landing-Page/Footer.jsx
  src/components/Landing-Page/HomeBanner.jsx
  src/components/Landing-Page/Navbar.jsx
  src/components/Landing-Page/Newsletter.jsx
  src/components/login/Login.jsx
  src/components/signup/SignUp.jsx
  src/defaultValues/DefaultValues.js
  src/feature/authActions.js
  src/feature/chatSlice.js
  src/layout/signup/SignUpLayout.jsx
  src/main.jsx
  src/schemas/index.js
Labels: enhancement

#17 Feature/chat backend
  app/Events/NewChatMessage.php
  app/Http/Controllers/API/ChatMessageController.php
  app/Http/Controllers/API/ChatRoomController.php
  app/Http/Resources/ChatRoomMembersResource.php
  app/Models/ChatMessage.php
  database/migrations/2023_04_12_130234_add_columns_to_chat_messages_table.php
  database/migrations/2023_04_13_092102_add_file_column_to_chat_messages_table.php
  package.json
  routes/api.php
Labels: enhancement

#18 feature/profile-backend: change fullname to username
  app/Http/Controllers/API/ProfileController.php
Labels: bug

#19 Feature/signup backend
  app/Http/Controllers/API/AuthController.php
Labels: bug

#21 Feature/chatpage
  package-lock.json
  package.json
  src/App.jsx
  src/PrivateRoute.jsx
  src/app/store.js
  src/assets/SignUpCamera.png
  src/components/chatHead/ChatHead.jsx
  src/components/chatMessage/ChatMessage.jsx
  src/components/input/Input.jsx
  src/components/login/Login.jsx
  src/components/message/Message.jsx
  src/components/signup/SignUp.jsx
  src/defaultValues/DefaultValues.js
  src/feature/authActions.js
  src/feature/chatRoomSlice.js
  src/feature/chatSlice.js
  src/feature/userSlice.js
  src/pages/chatPage/ChatPage.jsx
  src/routes/Router.jsx
  src/schemas/index.js
Labels: enhancement

#22 Feature/admin backend
  app/Http/Controllers/API/AdminController.php
  app/Http/Kernel.php
  app/Http/Middleware/AdminMiddleware.php
  app/Http/Requests/AdminLoginRequest.php
  app/Http/Requests/AdminRequest.php
  app/Models/Admin.php
  database/migrations/2023_04_14_074139_create_admins_table.php
  routes/api.php
Labels: enhancement

#23 Feature/signup backend
  app/Http/Requests/RegisterRequest.php
  app/Http/Resources/ChatRoomMembersResource.php
  app/Http/Resources/ChatRoomResource.php
  app/Http/Resources/RegisterResource.php
  app/Http/Resources/UserRoomsResource.php
Labels: bug

#24 Feature/group details
  .env
  .example.env
  backend/index.js
  backend/package-lock.json
  backend/package.json
  package-lock.json
  package.json
  public/_redirects
  src/App.jsx
  src/PrivateRoute.jsx
  src/app/store.js
  src/assets/uploadVideo.png
  src/colors.css
  src/colors.css.map
  src/components/Landing-Page/BodyContent.jsx
  src/components/Landing-Page/Footer.jsx
  src/components/Landing-Page/HomeBanner.jsx
  src/components/Landing-Page/Navbar.jsx
  src/components/Landing-Page/Newsletter.jsx
  src/components/chatHead/ChatHead.jsx
  src/components/chatMessage/ChatMessage.jsx
  src/components/groupDetails/GroupDetails.jsx
  src/components/input/Input.jsx
  src/components/layouts/SidebarLayout.jsx
  src/components/message/Message.jsx
  src/components/messages/Messages.jsx
  src/components/sidebar/ChatCard.jsx
  src/components/sidebar/Sidebar.jsx
  src/components/sidebar/UserCard.jsx
  src/components/signup/SignUp.jsx
  src/defaultValues/DefaultValues.js
  src/feature/chatRoomSlice.js
  src/feature/chatRooms.js
  src/feature/chatSlice.js
  src/index.css
  src/index.css.map
  src/pages/ChatComponent.jsx
  src/pages/chat/Chat.jsx
  src/pages/chatPage/ChatPage.jsx
  src/routes/Router.jsx
  src/schemas/index.js
  src/test.html
Labels: enhancement

#26 Feature/chatroom backend
  app/Http/Controllers/API/ChatRoomController.php
  app/Http/Controllers/API/RequestController.php
  app/Http/Resources/ChatRoomMembersResource.php
  app/Http/Resources/ChatRoomResource.php
  app/Models/ChatRoom.php
  database/migrations/2023_04_18_085234_add_description_column_to_chat_rooms_table.php
Labels: bug

#27 Feature/chat backend
  app/Http/Controllers/API/ChatMessageController.php
Labels: enhancement

#28 Feature/admin dashboard
  package-lock.json
  package.json
  src/app/store.js
  src/assets/Upload-Vector.svg
  src/assets/active_users.png
  src/assets/admin-search.png
  src/assets/admin.png
  src/assets/chat_room.png
  src/assets/close-button.png
  src/assets/close-svg.svg
  src/assets/edit-icon.svg
  src/assets/next.png
  src/assets/no-data.svg
  src/assets/pending_users.png
  src/assets/previous.png
  src/assets/rose.png
  src/assets/total_users.png
  src/assets/trash.svg
  src/assets/upload-image.png
  src/components/Landing-Page/Navbar.jsx
  src/components/admin/AdminNavbar.jsx
  src/components/admin/Card.jsx
  src/components/admin/Cards.jsx
  src/components/admin/Chatroom.jsx
  src/components/admin/ChatroomHeader.jsx
  src/components/admin/Chatrooms.jsx
  src/components/admin/NewChatroom.jsx
  src/components/admin/Pagination.jsx
  src/components/admin/UserSearch.jsx
  src/components/admin/modals/Delete.jsx
  src/components/admin/modals/Edit.jsx
  src/components/admin/modals/EditChatroomModal.jsx
  src/components/admin/modals/Users.jsx
  src/components/sidebar/ChatCard.jsx
  src/components/sidebar/Settings.jsx
  src/components/sidebar/Sidebar.jsx
  src/components/sidebar/UserCard.jsx
  src/feature/adminSlice.js
  src/layouts/AdminLayout.jsx
  src/layouts/MainLayout.jsx
  src/layouts/SidebarLayout.jsx
  src/layouts/SignUpLayout.jsx
  src/main.jsx
  src/pages/ChatComponent.jsx
  src/pages/admin/Admin.jsx
  src/pages/chats/Chats.jsx
  src/routes/Router.jsx
Labels: bug, enhancement

#32 Feature/user settings
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/app/store.js
  src/colors.scss
  src/components/generalSettings/index.jsx
  src/components/input/Input.jsx
  src/components/login/Login.jsx
  src/components/message/Message.jsx
  src/components/sidebar/Search.jsx
  src/components/sidebar/Sidebar.jsx
  src/components/sidebar/UserCard.jsx
  src/components/signup/SignUp.jsx
  src/components/userSettings/index.jsx
  src/defaultValues/DefaultValues.js
  src/feature/audioSlice.js
  src/feature/chatMessageSlice.js
  src/feature/chatRooms.js
  src/feature/chatSlice.js
  src/feature/userSlice.js
  src/main.jsx
  src/pages/ChatComponent.jsx
  src/pages/chat/Chat.jsx
  src/schemas/index.js
  src/svg/Icons.jsx
Labels: bug

#33 Feature/admin dashboard
  src/App.jsx
  src/components/admin/AdminNavbar.jsx
  src/components/admin/AdminPrivateRoute.jsx
  src/components/admin/Cards.jsx
  src/components/admin/Chatroom.jsx
  src/components/admin/ChatroomHeader.jsx
  src/components/admin/Chatrooms.jsx
  src/components/admin/NewChatroom.jsx
  src/components/admin/Pagination.jsx
  src/components/admin/UserSearch.jsx
  src/components/admin/modals/Delete.jsx
  src/components/admin/modals/EditChatroomModal.jsx
  src/components/admin/modals/Users.jsx
  src/components/adminLogin/index.jsx
  src/components/sidebar/ChatCard.jsx
  src/components/sidebar/Sidebar.jsx
  src/feature/adminSlice.js
  src/layouts/AdminLayout.jsx
  src/main.jsx
  src/pages/admin/Admin.jsx
  src/pages/chat/Chat.jsx
  src/routes/Router.jsx
Labels: enhancement
